services:
  app:
    image: muqrizmarzuki25/laraveldebian-php8.3:esilibus
    container_name: flower
    entrypoint:
      - /bin/sh
      - -c
      - |
        composer install --no-interaction --optimize-autoloader --prefer-dist
        npm install
        exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    ports:
      - "2007:80"
    volumes:
      - ./:/var/www
    restart: unless-stopped
    networks:
      - local-network

networks:
  local-network:
    external: true
    name: laravel-network
